{"content": {"suites": {"0": {"status": {"total_pass": 6, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 0, "total_error": 3}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_TC_OD001_subscribes_to_scan_topic", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_TC_OD002_processes_ROI_data", "rerun": "0"}, "2": {"status": "PASS", "message": "", "test_name": "test_TC_OD003_publishes_masked_scan", "rerun": "0"}, "3": {"status": "PASS", "message": "", "test_name": "test_TC_OD004_detects_obstacle_in_ROI", "rerun": "0"}, "4": {"status": "PASS", "message": "", "test_name": "test_TC_OD005_publishes_obstacle_status_true", "rerun": "0"}, "5": {"status": "ERROR", "message": "file /home/af/ros2_ws/src/ks_obstacle_detection/test/test_obstacle_detection.py, line 81\n  def test_TC_OD006_logs_warning_on_obstacle(ros2_node, caplog):\nE       fixture 'ros2_node' not found\n>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, cov, doctest_namespace, extra, include_metadata_in_junit_xml, metadata, monkeypatch, no_cover, node, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory\n>       use 'pytest --fixtures [testpath]' for help on them.\n\n/home/af/ros2_ws/src/ks_obstacle_detection/test/test_obstacle_detection.py:81\n", "test_name": "test_TC_OD006_logs_warning_on_obstacle", "rerun": "0"}, "6": {"status": "ERROR", "message": "file /home/af/ros2_ws/src/ks_obstacle_detection/test/test_obstacle_detection.py, line 95\n  def test_TC_OD007_logs_info_on_no_obstacles(ros2_node, caplog):\nE       fixture 'ros2_node' not found\n>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, cov, doctest_namespace, extra, include_metadata_in_junit_xml, metadata, monkeypatch, no_cover, node, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory\n>       use 'pytest --fixtures [testpath]' for help on them.\n\n/home/af/ros2_ws/src/ks_obstacle_detection/test/test_obstacle_detection.py:95\n", "test_name": "test_TC_OD007_logs_info_on_no_obstacles", "rerun": "0"}, "7": {"status": "PASS", "message": "", "test_name": "test_TC_OD008_calculates_dynamic_indices", "rerun": "0"}, "8": {"status": "ERROR", "message": "file /home/af/ros2_ws/src/ks_obstacle_detection/test/test_obstacle_detection.py, line 121\n  def test_TC_OD009_logs_errors_on_invalid_data(ros2_node, caplog):\nE       fixture 'ros2_node' not found\n>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, cov, doctest_namespace, extra, include_metadata_in_junit_xml, metadata, monkeypatch, no_cover, node, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory\n>       use 'pytest --fixtures [testpath]' for help on them.\n\n/home/af/ros2_ws/src/ks_obstacle_detection/test/test_obstacle_detection.py:121\n", "test_name": "test_TC_OD009_logs_errors_on_invalid_data", "rerun": "0"}}, "suite_name": "test/test_obstacle_detection.py"}}}, "date": "December 17, 2024", "start_time": 1734442311.4999294, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "6", "fail": "0", "skip": "0", "error": "3", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "9"}